
name: pr-verify
on:
  pull_request:
    branches:
          - main
            dev
            uat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.0.0

      - name: Build with dotnet
        run: dotnet build --configuration Release

