name: Pr Verify
on:
  pull_request:
    branches: ["main"]
jobs:
  build:
    name: Pr Verify
    runs-on: ubuntu-latest

    steps:
     - uses: actions/checkout@v4
     - name: Setup .net core
       uses: actions/setup-dontnet@v4
       with:
          dotnet-version: 8.0
     - name: Build with dotnet
       run: dotnet build --configuration Release
